services:
  django:
    image: proposer:v5
    build: .
    # ports:
    #   - "8000:8000"
    container_name: django
    volumes:
      - .:/app/
    depends_on:
      - ampq
  celery:
    image: proposer:v5
    command: python -m celery -A fhphome worker --pool=solo -l info
    depends_on:
        - ampq
#   ampq:
#     image: rabbitmq
#     volumes:
#       - ./ampq:/ampq
#     environment:
#       - RABBITMQ_DEFAULT_USER=admin
#       - RABBITMQ_DEFAULT_PASS=pass